### ISSUE TITLE
Add to awesome-cakephp

### ISSUE THREAD

**Issue by dereuromark** [Simbacode/xcrypto#1]
You might want to add this to https://github.com/FriendsOfCake/awesome-cakephp/tree/cake3

**Comment by mistaguy** [comment]
Great idea, let me put it under security

**Comment by mistaguy** [comment]
I have created a pull request https://github.com/FriendsOfCake/awesome-cakephp/pull/66

**Comment by dereuromark** [comment]
Sry, I was mislead by the "You can as well clone the library in your cakePHP vendor" slogan :)
